

(* Sample grammar in ebnf notation *)

track = <blank> statement (<blank> | <newline> statement)*

statement = section
  | comment
  | channel-command
  | variable-block
  | word (<space> exp)+
  
variable-block = <"let" space> variable*

channel-command
    = channel <space> parameter* <param-sep space> pattern effect* 
    | channel exp

channel   = <"p" space "\""> name <"\"" space>
parameter = <space param-sep space> word <space> exp*
effect    = <space fx-sep    space> word <space> exp*
pattern   = pattern-function space exp | "silence"
variable  = (name <space>)+ "=" <space> value

<pattern-function> = "s"|"n"|"note"



comment = <"--"> (seg-command | space | #"\b[^\n^]*\b")*
seg-command = <"@"> name

section = <#"do"> (<indent> statement)+
indent = #"\n +"


<exp> = word
    | string
    | integer
    | float
    | "(" <blank> exp (<space> exp)* <blank> ")"
    | operator

integer = #'[0-9]+'
float = #'[0-9]+.[0-9]+'

operator = #"\B(\+|\-|\/|\*|\=|\<|\>|\.|\#|\$|\^|\&|\!|\%|\~|\|)+\B"

param = #'\w+'
param_name = #'\w+'
param-sep = "$"
fx-sep = "#"

blank = newline* | space*
newline = "\n"
name = #'\w+'
value = exp
<word> = #"(?!(let|do|--|[0-9]))\b\w+" <space>*
comma = ','
space = #'\s'*

string = #"\"[^\"]*\""

